GET http://localhost:3000/classes

GET http://localhost:3000/classes?id=2

POST http://localhost:3000/classes
content-type: application/json

{
    "id": "1",
    "name": "Turma 1"
}

PUT http://localhost:3000/classes
content-type: application/json

{
    "id": "1",
    "name": "Turma Um"
}

DELETE http://localhost:3000/classes
content-type: application/json

{
    "id": "1",
}