GET http://localhost:3000/classes/searchClasses
content-type: application/json

{
    "token": "emh7s79mvcema880k82c99"
}

GET http://localhost:3000/classes/searchClasses?name=Turma 1 ADS
content-type: application/json

{
    "token": "emh7s79mvcema880k82c99"
}

GET http://localhost:3000/classes/searchClasses?discipline=IHC
content-type: application/json

{
    "token": "emh7s79mvcema880k82c99"
}

GET http://localhost:3000/classes/searchClasses?name=Turma 1 ADS&discipline=algoritmo
content-type: application/json

{
    "token": "emh7s79mvcema880k82c99"
}

GET http://localhost:3000/classes/getClass?id=1
content-type: application/json

{
    "token": "emh7s79mvcema880k82c99"
}

GET http://localhost:3000/classes/getUserClasses
content-type: application/json

{
    "token": "emh7s79mvcema880k82c99"
}

POST http://localhost:3000/classes/createClass
content-type: application/json

{
    "name": "Turma 1 ADS",
    "section": "1",
    "discipline": "algoritmo",
    "room": "1",
    "token": "emh7s79mvcema880k82c99"
}

POST http://localhost:3000/classes/createClass
content-type: application/json

{
    "name": "Turma 1 ADS",
    "section": "1",
    "discipline": "IHC",
    "room": "1",
    "token": "emh7s79mvcema880k82c99"
}

POST http://localhost:3000/classes/joinClass
content-type: application/json

{
    "id": "1",
    "token": "emh7s79mvcema880k82c99"
}

DELETE http://localhost:3000/classes/leaveClass
content-type: application/json

{
    "id": "1",
    "token": "emh7s79mvcema880k82c99"
}

PUT http://localhost:3000/classes/updateClass
content-type: application/json

{
    "id": "1",
    "name": "Turma 2 ADS",
    "token": "emh7s79mvcema880k82c99"
}

DELETE http://localhost:3000/classes/deleteClass
content-type: application/json

{
    "id": "1",
    "token": "emh7s79mvcema880k82c99"
}