GET http://localhost:3000/warnings/getClassWarnings?class_id=1
content-type: application/json

{
    "token": "4qh2ntasnrtet6jb1ul10c"
}

POST http://localhost:3000/warnings/createWarning
content-type: application/json

{
    "class_id": "1",
    "message": "Aviso urgente!",
    "token": "4qh2ntasnrtet6jb1ul10c"
}

PUT http://localhost:3000/warnings/updateWarning
content-type: application/json

{
    "id": "1",
    "message": "Aviso não tão urgente",
    "token": "4qh2ntasnrtet6jb1ul10c"
}

DELETE http://localhost:3000/warnings/deleteWarning
content-type: application/json

{
    "id": "1",
    "token": "4qh2ntasnrtet6jb1ul10c"
}