GET http://localhost:3000/classes/getUserClasses
content-type: application/json

{
    "token": "meumnp16730lod3d00q9s"
}

POST http://localhost:3000/classes/createClass
content-type: application/json

{
    "name": "Matematica 101",
    "token": "meumnp16730lod3d00q9s"
}

PUT http://localhost:3000/classes/updateClass
content-type: application/json

{
    "id": "1",
    "name": "Matemática 100",
    "token": "meumnp16730lod3d00q9s"
}

DELETE http://localhost:3000/classes/deleteClass
content-type: application/json

{
    "id": "1",
    "token": "meumnp16730lod3d00q9s"
}